### ISSUE TITLE
I've kept the ProcmonConfiguration.PMC name because that's what SysInternals has always referred to it as. I don't want people to think that this is using an entirely new file format when they may already have PMC's lying around.

### ISSUE THREAD

**Issue by oasec1** [Rurik/Noriben#32] opened 2019-08-29 16:48 UTC
I've kept the ProcmonConfiguration.PMC name because that's what SysInternals has always referred to it as. I don't want people to think that this is using an entirely new file format when they may already have PMC's lying around.

However, this should be doable with the --filter (-f) option and pointing it to another filename. It could even be something remotely shared (SMB) if ransomware is corrupting it.

This is equivalent to running: procmon.exe /BackingFile "Noriben.pml" /Quiet /Minimized /LoadConfig "A.DAT", where I have ProcmonConfiguration.PMC named A.DAT.

That appears to work perfectly.  Now 1 more thought, it appears also to be encrypting the.pml file. I know procmon allows you to change the name of that file with the commandline option of /BackingFile  can  you also do that with the --f or -f and change the output log file name?  I dont want to change the name just the log files extension.

Please let me know if that works for you

_Originally posted by @Rurik in https://github.com/Rurik/Noriben/issues/30#issuecomment-510563193_

**Comment by jedisct1** [comment] 2019-08-29 17:00
Longest title ever!

**Comment by barrypittman** [comment] 2019-08-29 17:26
LOL!

**Comment by Rurik** [comment] 2020-04-05 18:54
Closing as duplicate of #33

**Closed by Rurik** 2020-04-05 18:54 UTC
